parameters:
    env(APP_LOCALE): en
    locale: '%env(resolve:APP_LOCALE)%'

framework:
    ide: 'phpstorm://open?file=%%f&line=%%l'
    cache:
        default_memcached_provider: 'memcached://localhost'
        pools:
            doctrine.result_cache_pool:
                adapter: 'cache.adapter.%env(resolve:DOCTRINE_CACHE_DRIVER)%'
            doctrine.system_cache_pool:
                adapter: 'cache.adapter.%env(resolve:DOCTRINE_CACHE_DRIVER)%'
    esi: { enabled: true }
    translator:
        fallbacks: ["%locale%"]
        logging: false
    secret: "%env(APP_SECRET)%"
    router:
        strict_requirements: ~
    form:            ~
    csrf_protection: true
    validation:      { enable_annotations: false }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    fragments: { path: /_fragment }
    http_method_override: true
