SWP\Component\Bridge\Model\Package:
    properties:
        slugline:
            - Length:
                  min: 0
                  max: 200
                  minMessage: 'Slug must be at least {{ limit }} characters long'
                  maxMessage: 'Slug cannot be longer than {{ limit }} characters'
