swp_api_content_list_related_articles:
  path: /api/{version}/content/articles/{id}/related/
  defaults: { _controller: SWP\Bundle\ContentBundle\Controller\RelatedArticleController::listAction, version: v2 }
  requirements:
    id: '\d+'
  methods: [GET]
  options:
    expose: true

swp_content:
  resource: '@SWPContentBundle/Controller'
  type: annotation
