Symfony\Cmf\Bundle\RoutingBundle\Model\Route:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api, api_routes_list]
            type: integer
        content:
            expose: true
            groups: [api]
            exclude_if: "object.getTenantCode() != service('swp_multi_tenancy.tenant_context').getTenant().getCode()"
        staticPrefix:
            expose: true
            groups: [api]
            type: string
        variablePattern:
            expose: true
            groups: [api]
            type: string
