Symfony\Cmf\Bundle\RoutingBundle\Model\Route:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api, api_routes_list]
            type: integer
        content:
            expose: true
            groups: [api]
            maxDepth: 1
            exclude_if: "!is_granted('view',object)"
        staticPrefix:
            expose: true
            groups: [api]
            type: string
        variablePattern:
            expose: true
            groups: [api]
            type: string
